import serial, time, sys
ARDUINO_port = serial.Serial('COM17', 115200)
ARDUINO_port.flushInput()
#time.sleep(2)
ARDUINO2 = serial.Serial('COM3', 115200)
ARDUINO2.flushInput()
########    VARIABLES GLOBALES  ################
print("¿Ingrese bebida?")
nombre = int(sys.stdin.readline().rstrip())
print(nombre, flush=True)

if nombre == 1:

   print(f"Bebida : {nombre}", flush=True)
   #time.sleep(10)

   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("qa", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1a", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("1", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("1b", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("qc", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1c", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("qd", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1d", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("qe", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1e", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("1000001", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("1f", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("1000000", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("1g", flush=True)

   time.sleep(3)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("qh", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1h", flush=True)

   time.sleep(3)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("qi", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1i", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("100001", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("1j", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("100000", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("1k", flush=True)

   time.sleep(3)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("ql", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1l", flush=True)

   time.sleep(3)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("qm", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1m", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("10001", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("1n", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("10000", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("1o", flush=True)

   time.sleep(3)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("qp", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1p", flush=True)

   time.sleep(3)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("qq", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1q", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("qr", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1r", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("qt", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1t", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("0", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("1u", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("qv", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1v", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("qw", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1w", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("qx", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1x", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("qy", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("1y", flush=True)

   time.sleep(9)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("001", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("1z", flush=True)

   time.sleep(3)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("000", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("1A", flush=True)
   print("end", flush=True)


elif nombre == 2:
   print(f"Bebida : {nombre}", flush=True)
   #time.sleep(10)

   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("wa", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2a", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("1", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("2b", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("wc", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2c", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("wd", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2d", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("we", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2e", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("1000001", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("2f", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("1000000", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("2g", flush=True)

   time.sleep(3)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("wh", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2h", flush=True)

   time.sleep(3)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("wi", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2i", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("100001", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("2j", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("100000", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("2k", flush=True)

   time.sleep(3)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("wl", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2l", flush=True)

   time.sleep(3)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("wm", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2m", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("10001", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("2n", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("10000", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("2o", flush=True)

   time.sleep(3)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("wp", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2p", flush=True)

   time.sleep(3)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("wq", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2q", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("wr", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2r", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("wt", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2t", flush=True)

   time.sleep(5)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("0", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("2u", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("wv", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2v", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("ww", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2w", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("wx", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2x", flush=True)

   time.sleep(5)
   ARDUINO2.reset_input_buffer()
   VarCuaTxt2_c = bytes("wy", 'utf-8')
   ARDUINO2.write(VarCuaTxt2_c)
   ARDUINO2.reset_input_buffer()
   print("2y", flush=True)

   time.sleep(9)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("001", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("2z", flush=True)

   time.sleep(3)
   ARDUINO_port.reset_input_buffer()
   VarCuaTxt2_c = bytes("000", 'utf-8')
   ARDUINO_port.write(VarCuaTxt2_c)
   ARDUINO_port.reset_input_buffer()
   print("2A", flush=True)
